robot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  robot_mobile:
    type: "robot_controller/RobotController"
    left_wheel: "wheelFL_joint"
    right_wheel: "wheelFR_joint"

  
